FYP Web Development/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify, session, current_app
from flask_login import login_required, current_user
from .app import db, mail
from .models import admin, staff, student, announcement, roomlist, roombookings, eventbookings, registeredfaces, roomaccesslog, feedback, report, attr_names,relations
from sqlalchemy import desc, and_, select
from datetime import datetime, timedelta
import json
import urllib.request
import os
import re
from os.path import join, dirname, realpath
from flask_mail import Mail, Message
from werkzeug.utils import secure_filename

views = Blueprint('views', __name__)

os.chdir('D:/Educational/FYP Web Development/website')

@views.route('/')#url of homepage
def home():
    announcements = db.session.query(announcement).order_by(desc(announcement.PostDate)).all()
    rooms = db.session.query(roomlist)
    studList = db.session.query(student)
    staffList = db.session.query(staff)
    rBookList = db.session.query(roombookings)
    eBookList = db.session.query(eventbookings)
    if current_user.is_authenticated:
        if current_user.is_Staff():
            return redirect(url_for('views.homeStaff'))
        elif current_user.is_Admin():
            return redirect(url_for('views.homeAdmin'))
        elif current_user.is_Student():
            return redirect(url_for('views.homeStud'))
        else:
            return render_template("home.html", user=current_user, announcements=announcements)
    else:
        return render_template("home.html", user=current_user, roomlist=rooms, staff=staffList,student=studList, roombookings=rBookList,eventbookings=eBookList, 
                               announcements=announcements)

@views.route('/homeStud')
@login_required
def homeStud():
    currDateTime = datetime.now()
    currDate = currDateTime.strftime("%d-%m-%Y")
    announcements = db.session.query(announcement).order_by(desc(announcement.PostDate)).all()
    if current_user.is_Student():
        rooms = db.session.query(roomlist)
        studList = db.session.query(student)
        staffList = db.session.query(staff)
        rBookList = db.session.query(roombookings)
        eBookList = db.session.query(eventbookings)
        regFaceExist = db.session.query(registeredfaces).filter_by(StudID = current_user.StudID).first()
        return render_template("homeStud.html", user=current_user, roomlist=rooms, staff=staffList,student=studList, roombookings=rBookList, eventbookings=eBookList, 
                               currentDate = currDate,regFaceExist=regFaceExist, announcements=announcements, is_Student=True, is_Staff=False, is_Admin=False)
    else:
        flash('Only students allowed on that URL.', category='error')
        if current_user.is_Staff():
            return redirect(url_for('views.homeStaff'))
        elif current_user.is_Admin():
            return redirect(url_for('views.homeAdmin'))

@views.route('/homeStaff')
@login_required
def homeStaff():
    currDateTime = datetime.now()
    currDate = currDateTime.strftime("%d-%m-%Y")
    announcements = db.session.query(announcement).order_by(desc(announcement.PostDate)).all()
    if current_user.is_Staff():
        rooms = db.session.query(roomlist)
        studList = db.session.query(student)
        staffList = db.session.query(staff)
        rBookList = db.session.query(roombookings)
        eBookList = db.session.query(eventbookings)
        regFaceExist = db.session.query(registeredfaces).filter_by(StaffID = current_user.StaffID).first()
        return render_template("homeStaff.html", user=current_user, roomlist=rooms, staff=staffList,student=studList, roombookings=rBookList, eventbookings=eBookList, 
                               currentDate = currDate, regFaceExist=regFaceExist, announcements=announcements, is_Student=False, is_Staff=True, is_Admin=False)
    else:
        flash('Only staff members allowed on that URL.', category='error')
        if current_user.is_Student():
            return redirect(url_for('views.homeStud'))
        elif current_user.is_Admin():
            return redirect(url_for('views.homeAdmin'))

@views.route('/homeAdmin')
@login_required
def homeAdmin():
    if current_user.is_Admin():
        rooms = db.session.query(roomlist)
        studList = db.session.query(student)
        staffList = db.session.query(staff)
        rBookList = db.session.query(roombookings)
        eBookList = db.session.query(eventbookings)
        return render_template("homeAdmin.html", user=current_user, roomlist=rooms, staff=staffList,student=studList, roombookings=rBookList,eventbookings=eBookList, is_Student=False, is_Staff=False, is_Admin=True)
    else:
        flash('Only admin allowed on that URL.', category='error')
        if current_user.is_Staff():
            return redirect(url_for('views.homeStaff'))
        elif current_user.is_Student():
            return redirect(url_for('views.homeStud'))

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])
UPLOAD_FOLDER = 'static\\uploads\\'
UPLOAD_FOLDER_ABSOLUTE = "D:/Educational/FYP Web Development/website/static/uploads"
basedir = os.path.abspath(os.path.dirname(__file__))

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@views.route('/', methods=['POST'])
def upload_image():
    if 'file' not in request.files:
        flash('No file part')
        return redirect(request.url)
    file = request.files['file']
    if file.filename == '':
        flash('No image selected for uploading')
        return redirect(request.url)
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(UPLOAD_FOLDER, filename))
        #print('upload_image filename: ' + filename)
        flash('Image successfully uploaded and displayed below')
        return render_template('index.html', filename=filename)
    else:
        flash('Allowed image types are - png, jpg, jpeg, gif')
        return redirect(request.url)
 
@views.route('/display/<filename>')
def display_image(filename):
    #print('display_image filename: ' + filename)
    return redirect(url_for('static', filename='uploads/'+filename), code=301)
     
@views.route('/ManageAnnouncements', methods=['GET','POST'])
@login_required
def ManagemetAnnouncements():
    if current_user.is_Admin():
        if request.method == 'POST': 
            ATitle = request.form.get('ATitle')#Gets the data from the HTML
            AContent = request.form.get('AContent')

            if len(ATitle) < 1:
                flash('Please Enter Announcement Title', category='error')
            elif len(AContent) < 1:
                flash('Please Enter Announcement Content', category='error') 
            else:
                current_dateTime = datetime.now()
                new_announcement = announcement(AdminID=current_user.AdminID,PostDate=current_dateTime,Title=ATitle,Content=AContent)  #providing the schema for the note
                db.session.add(new_announcement) #adding the note to the database 
                db.session.commit()
                flash('Announcement Added!', category='success')
                print("Announcement Added somehow")
        
        announcements = db.session.query(announcement).order_by(desc(announcement.PostDate)).all()
        return render_template("manageAnnounce.html", user=current_user, announcements=announcements, is_Student=False, is_Staff=False, is_Admin=True)
    else:
        flash('Only admin allowed on that URL.', category='error')
        if current_user.is_Staff():
            return redirect(url_for('views.homeStaff'))
        elif current_user.is_Student():
            return redirect(url_for('views.homeStud'))

@views.route('/updateAnnounce/', methods = ['POST'])
def updateAnnounce():
    if request.method == "POST":
        Announce = db.session.query(announcement).filter_by(AnnounceID= request.form.get('AnnounceID')).first()
        
        Announce.Title = request.form.get('Title')#Gets the data from the HTML
        Announce.Content = request.form.get('Content')

        db.session.commit()
        flash("Announcement is updated")
        return redirect(url_for('views.ManagemetAnnouncements'))

@views.route('/delete-announcement', methods=['POST'])
def delete_announcement():  
    Announcement = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
    AnnounceID = Announcement['AnnounceId']
    Announcement = db.session.query(announcement).get(AnnounceID)
    if Announcement:
        if current_user.is_Admin():
            db.session.delete(Announcement)
            db.session.commit()

    return jsonify({})

@views.route('/ManageRooms', methods=['GET','POST'])
@login_required
def ManagementRooms():
    if current_user.is_Admin():
        if request.method == 'POST': 
            AdminID = current_user.AdminID
            RoomName = request.form.get('roomName')#Gets the data from the HTML
            RoomInfo = request.form.get('roomInfo')
            RoomType = request.form.get('roomType')
            RoomStatus = request.form.get('roomStatus')
            img = request.files['file']
            newname = img.filename.replace(" ", "_")
            newname = re.sub(r"[\([{})\]]", "", newname)
            roomIMG = "roomImages/" + newname
            
            roomExist = db.session.query(roomlist).filter_by(RoomName = RoomName).first()
            if roomExist:
                flash('Room already in the list.', category='error')
            else:
                if img and allowed_file(img.filename):
                    filename = secure_filename(img.filename)
                    img.save(os.path.join(basedir, UPLOAD_FOLDER, "roomImages/" + filename))
                    #print('upload_image filename: ' + filename)
                    flash('Image successfully uploaded')
                    #providing the schema for the note

FYP Web Development/website/templates/AccessLogView.html
{% extends "base.html" %}
<title>{% block title %} Face Manager {% endblock %}</title>

{% block PageTitle%}
    <br/>
    <center><h2>Room Access Log - ADMINISTRATION</h2></center>
{% endblock %}

{% block content%}
<br/>
<div class="flex-container container-fluid" style="">
    <div class="row">
        <div class="col md-12">
            <button class="btn btn-secondary" style="margin-bottom:10px;" onclick="location.href = '/homeAdmin';">Go Back</button>
            <div class="jumbotron p-3">
                <table id="RAccessLogTable" class="table table-hover table-dark display">
                    <thead>
                        <tr>
                            <th>RAccessLogID</th>
                            <th>Room Name</th>
                            <th>Student/Staff Name</th>
                            <th>Student/Staff ID</th>
                            <th>Status</th>
                            <th>Timestamp</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    {% for r in roomaccesslog %}
                        <tr>
                            <td>{{r.rmaID}}</td>
                            {% for rm in roomlist %}
                                {%if rm.RoomID == r.RoomID%}
                                <td>{{rm.RoomName}}</td>
                                {%endif%}
                            {% endfor %}
                            {% if r.StudID != None %}
                                {%for stud in student %}
                                    {% if stud.StudID == r.StudID %}
                                    <td>{{stud.StudName}}</td>
                                    <td>{{stud.StudID}}</td>
                                    {% endif %}
                                {% endfor %}
                            {% elif r.StaffID != None %}
                                {%for staff in staff %}
                                    {% if staff.StaffID == r.StaffID %}
                                    <td>{{staff.StaffName}}</td>
                                    <td>{{staff.StaffID}}</td>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            {% if r.Status == 0%}
                                <td>PASS</td>
                            {% elif r.Status == 1%}
                                <td>FAIL</td>
                            {%endif%}
                            <td>{{r.Timestamp}}</td>
                            <td>
                                <a href="/deleteRAccessLog/{{r.rmaID}}/" class="btn btn-danger btn-xs" onclick="return confirm('Delete room access log from listing?')">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            <!</div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.js"></script>
<script type = "text/javascript" src = "{{ url_for('static', filename='room.js')}}"></script>
{% endblock %}

FYP Web Development/website/templates/adminAddRBook.html
{% extends "base.html" %}
<title>{% block title %} Room Bookings Manager {% endblock %}</title>

{% block PageTitle%}
    <br/>
    <center><h2>Room Bookings (Add Room) - ADMINISTRATION</h2></center>
{% endblock %}

{% block content%}
<br/>
<div class="flex-container container-fluid" style="">
    <div class="row">
        <div class="col md-12">
            <button class="btn btn-secondary" style="margin-bottom:10px;" onclick="location.href = '/ManageRBookings';">Go Back</button>
            <div class="addRBookContainer m-3 border-top">
                <h4 class="font-weight-bold pb-3 mt-3 pl-lg-5 mb-0" style="text-align: center;">Current Room Bookings</h4> *Please click on a date to add a booking
                    <div class="float-right">
                        <b>Room: </b> 
                        <select id="selector">
                            <option value="all">All</option>
                            {% for r in roomlist %}
                            {%if r.RoomStatus != "Closed" and r.RoomType == "Normal Room"%}
                            <option value="{{r.RoomID}}">{{r.RoomName}}</option>
                            {%endif%}
                            {% endfor %}
                        </select>
                    </div>
                    <br/><br/>
                    <div id="modaladdRBook" class="modal fade" role="dialog">
                        <div class="modal-dialog modal-lg" style="width:90%">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Add Room Booking - ADMIN</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="container-fluid">
                                    <form action="" method="POST" enctype="multipart/form-data">
                                        <div class="form-group">
                                            <label>Is this room booking for a student or staff?:</label></br>
                                            <select id="rBookType" name="rBookType" required>
                                                <option disabled selected value> -- select an option -- </option>
                                                <option value="student">Student</option>
                                                <option value="staff">Staff</option>
                                            </select>
                                        </div>
                                        <div class="form-group" id="userType">
                                            <div id="typeStudent" style="display:none;">
                                                <p>Student ID:
                                                    <select class="js-example-basic-single" id="studentid" name="studentid">
                                                        <option disabled selected value> -- select an option -- </option>
                                                        {%for stud in student%}
                                                        <option value="{{stud.StudID}}"> {{stud.StudID + " - " + stud.StudName}} </option>
                                                        {%endfor%}
                                                    </select>
                                                </p>
                                            </div>
                                            <div id="typeStaff" style="display:none;">
                                                <p>Staff ID:
                                                    <select class="js-example-basic-single" id="staffid" name="staffid">
                                                        <option disabled selected value> -- select an option -- </option>
                                                        {%for staff in staff%}
                                                        <option value="{{staff.StaffID}}"> {{staff.StaffID + " - " + staff.StaffName}} </option>
                                                        {%endfor%}
                                                    </select>
                                                </p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Please select the room to book:</label></br>
                                            <select id="roomSelect" name="roomSelect" required>
                                                <option disabled selected value> -- select an option -- </option>
                                                {% for r in roomlist %}
                                                    {%if r.RoomStatus != "Closed" and r.RoomType == "Normal Room"%}
                                                    <option value="{{r.RoomID}}">{{r.RoomName}}</option>
                                                    {%endif%}
                                                {% endfor %}
                                            </select><br/>
                                            <div class="row ml-1 mt-1">
                                                <img id="roomPreview" src="placeholder.png" height="150" width="300" alt=""/>
                                                <pre><span id="roomInfoPreview"></span></pre>
                                            </div>
                                        </div>
                                        <h6>Each Room Booking is only allowed to be 2 hours long</h6>
                                        <div class="form-group" id="startEndRBook">
                                            <p>Start: 
                                                <input type="date" id="rbookstart" name="rbookstart"> 
                                                <select id="rbooktimeStart" name="rbooktimeStart">
                                                    <option disabled selected value> -- select an option -- </option>
                                                    <option value="09:00:00">09:00 AM</option>
                                                    <option value="10:00:00">10:00 AM</option>
                                                    <option value="11:00:00">11:00 AM</option>
                                                    <option value="12:00:00">12:00 PM</option>
                                                    <option value="13:00:00">01:00 PM</option>
                                                    <option value="14:00:00">02:00 PM</option>
                                                    <option value="15:00:00">03:00 PM</option>
                                                    <option value="16:00:00">04:00 PM</option>
                                                    <option value="17:00:00">05:00 PM</option>
                                                    <option value="18:00:00">06:00 PM</option>
                                                    <option value="19:00:00">07:00 PM</option>
                                                    <option value="20:00:00">08:00 PM</option>
                                                </select>
                                            </p>
                                            <p>End: 
                                                <input type="date" id="rbookend" name="rbookend"> 
                                                <select id="rbooktimeEnd" name="rbooktimeEnd">
                                                    <option disabled selected value> -- select an option -- </option>
                                                    <option value="09:00:00">09:00 AM</option>
                                                    <option value="10:00:00">10:00 AM</option>
                                                    <option value="11:00:00">11:00 AM</option>
                                                    <option value="12:00:00">12:00 PM</option>
                                                    <option value="13:00:00">01:00 PM</option>
                                                    <option value="14:00:00">02:00 PM</option>
                                                    <option value="15:00:00">03:00 PM</option>
                                                    <option value="16:00:00">04:00 PM</option>
                                                    <option value="17:00:00">05:00 PM</option>
                                                    <option value="18:00:00">06:00 PM</option>
                                                    <option value="19:00:00">07:00 PM</option>
                                                    <option value="20:00:00">08:00 PM</option>
                                                    <option value="21:00:00">09:00 PM</option>
                                                </select>
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Purpose of Booking:</label></br>
                                            <textarea 
                                                name = "RBookPurpose" 
                                                id="RBookPurpose"
                                                class="form-control pull-left" 
                                                rows="3" 
                                                cols="2" 
                                                v-model="RBookPurpose" 
                                                placeholder="Room Booking Purpose" 
                                            required></textarea><br>
                                        </div>
                                        <div class="form-group">
                                            <button class="btn btn-primary mt-4" type="submit">Submit</button>
                                            <button type="button" class="btn btn-default mt-4 btn-outline-secondary" data-dismiss="modal" onclick="this.form.reset();">Close</button>
                                        </div>
                                    </form>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="calendar">

                    </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.js"></script>
<script type = "text/javascript" src = "{{ url_for('static', filename='room.js')}}"></script>
{% endblock %}

FYP Web Development/website/templates/manageAnnounce.html
{% extends "base.html" %}
<title>{% block title %} Announcements {% endblock %}</title>
{% block content%}
<br/>
<div class="row">
    <section class="two-column-list mb-sm-5 pr-lg-3 container-fluid" id="two-column-list">
        <div class="flex-container container-fluid" style="">
            <div class="row">
                <div class="col-lg-6 pr-0">
                    <section aria-label="Announcements" class="announcements">
                        <h4 class="font-weight-bold border-bottom pb-3 mt-3 mb-0 pr-5" style="text-align: center;">Announcements - ADMINISTRATION</h4>
                        <ul class="list-group list-group-flush" id="announcements">
                            {% for a in announcements %}
                            <li class="list-group-item">
                                <p>{{ a.PostDate.strftime('%Y-%m-%d') }}</p>
                                <button type="button" class="close display:inline-block; position:relative;" onClick="confirmDeleteAnnnouncement({{ a.AnnounceID }});">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h5><a href="/updateAnnounce/{{a.AnnounceID}}" data-toggle="modal" data-target="#modaleditannounce{{a.AnnounceID}}">{{ a.Title }}</a></h5>
                                <hr/>
                            </li>
                            <!--UPDATE ANNOUNCEMENT MODAL-->
                            <div id="modaleditannounce{{a.AnnounceID}}" class="modal fade" role="dialog">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Edit Room</h4>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{{url_for('views.updateAnnounce')}}" method="POST">
                                                <div class="form-group">
                                                    <label>Room Name:</label>
                                                    <input type="hidden" id="AnnounceID" name="AnnounceID" value="{{a.AnnounceID}}">
                                                    <input type="text" class="form-control" id="Title" name="Title" value="{{a.Title}}" >
                                                </div>
                                                <div class="form-group">
                                                    <label>Announcement Content</label>
                                                    <textarea 
                                                        name = "Content" 
                                                        id="Content" 
                                                        class="form-control pull-left" 
                                                        rows="3" 
                                                        cols="2" 
                                                        v-model="updateAnnounce"
                                                    required>{{a.Content}}</textarea><br>
                                                </div>
                                                <div class="form-group">
                                                    <button class="btn btn-primary mt-4" type="submit">Edit Room</button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </ul>
                    </section>
                </div>
                <div class="col-lg-6 pl-0">
                        <div class="container mt-5">
                            <form name="formA" method="POST" class="card card-color form-border">
                              <div class="card-header px-3">
                               <p class="font-weight-bold"> Add new Announcement</p>
                              </div>
                              <div class="card-block mx-2">
                                <label for="ATitle">Title</label>
                                <input
                                    type="text"
                                    class="form-control"
                                    id = "ATitle"
                                    name = "ATitle"
                                    placeholder = "Enter Announcement Title"
                                required/>
                              </div>
                              <div class="card-block mx-2">
                                <label for="AContent">Content</label>
                                <textarea name = "AContent" id="AContent" class="form-control pull-left" rows="3" cols="2" v-model="newAnnouncement" placeholder="New announcement details" required></textarea>
                              </div>
                              <div class="card-footer px-3">
                                <button type="submit" class="btn btn-sm btn-success ml-2" onclick="submit_form()">Add Announcement</button>
                              </div>
                            </form>
                            <!--<p v-if="error" class="error mt-2 alert alert-danger"> {{ error }}</p>--><br/>
                            <button class="btn btn-secondary" onclick="location.href = '/homeAdmin';">Go Back</button>
                        </div>
                </div>
            </div>
        </div>
    </section>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.js"></script>
<script type = "text/javascript" src = "{{ url_for('static', filename='announcement.js')}}"></script>
{% endblock %}

FYP Web Development/website/templates/registerSelect.html
{% extends "base.html" %}
<title>{% block title %} Student Registration {% endblock %}</title>
{% block content%}
<div class="flex-container container">
    <form method="POST">
        <br />
        <h3 align="center">Select Registration for Staff or Student</h3>
        <br />
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <button id="registerStud" class="btn btn-primary btn-lg" type="reset">STUDENT</button>
                    <button id="registerStaff" class="btn btn-secondary btn-lg" type="reset">STAFF</button>
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    document.getElementById("registerStud").onclick = function () {
        location.href = "/studRegister";
    };
    document.getElementById("registerStaff").onclick = function () {
        location.href = "/staffRegister";
    };
</script>
{% endblock %}